### ISSUE TITLE
Tasks deletion

### ISSUE THREAD

**Issue by Hypro999** [Hypro999/Recruitments-Portal#7]
When a candidate or pitch gets deleted, the corresponding task also needs to get deleted. Otherwise this will leave behind residual tasks that can't easily be deleted (i.e. through the admin panel) due to missing foreignkeys.

**Comment by sanchit-ahuja** [comment]
For this, you just need a foreign key to candidate and pitch in task which would enable a complete deletion.

**Comment by Hypro999** [comment]
Could work,  and it would also be useful in other ways down the line.
